apiVersion: apps/v1
kind: Deployment
metadata:
  name: morda-d
  labels:
    app: morda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morda
  template:
    metadata:
      labels:
        app: morda
    spec:
      containers:
        - name: morda
          image: morda:0.1.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '0.5'
              memory: 150Mi
            requests:
              cpu: '0.25'
              memory: 75Mi