apiVersion: v1
kind: Service
metadata:
  name: morda
  labels:
    app: morda
spec:
  type: LoadBalancer
  selector:
    app: morda
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 8080
