apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
